- name: slurm install
  hosts: localhost
  tasks:
    - name: check libslurm.la
      ansible.builtin.stat:
        path: /home/lory/sw_install/gcc-13.4.0/slurm-24.11.6/lib/libslurm.la
      register: check_slurm
    - name: Install slurm
      when: not check_slurm.stat.exists
      block:
        - name: install requirements
          become: true
          ansible.builtin.apt:
            autoclean: true
            pkg: 
              - libpam0g
              - libpam0g-dev
              - libpam-apparmor
              - libpam-cgroup
              - libpam-mklocaluser
              - libpam-modules
              - libpam-modules-bin
              - libpam-mount
              - libpam-mount-bin
              - libpam-runtime
              - libpam-script
              - libpam-systemd
              - libmariadb3
              - libmariadb-dev
              - libmariadb-dev-compat
              - mariadb-backup
              - mariadb-client
              - mariadb-common
              - mariadb-plugin-connect
              - mariadb-server
              - mycli
              - jwt
              - libjwt2
              - libjwt-dev
              - libhttp-parser2.9
              - libhttp-parser-dev
              - hdf5-tools
              - hdf-compass
              - h5utils
              - libhdf5-dev
              - libhdf5-103-1t64
              - libhdf5-cpp-103-1t64
              - libhdf5-fortran-102t64
              - freeipmi
              - freeipmi-tools
              - freeipmi-ipmidetect
              - freeipmi-common
              - libfreeipmi17
              - libfreeipmi-dev
              - rrdtool
              - librrd8t64
              - librrd-dev
              - libgtk2.0-0t64
              - libgtk2.0-bin
              - libgtk2.0-common
              - libgtk2.0-dev
              - libglib2.0-0t64
              - libglib2.0-bin
              - libglib2.0-dev
              - libglib2.0-dev-bin
              - librdkafka++1
              - librdkafka1
              - librdkafka-dev
              - man2html
              - man2html-base
              - libsystemd-dev
              - libdbus-1-dev
              - check
              - cppcheck
              - libbpf1
              - libbpf-dev
              - libyaml-0-2
              - libyaml-appconfig-perl
              - libyaml-cpp-dev
              - libyaml-cpp0.8
              - libyaml-dev
              - libyaml-perl
              - libyaml-pp-perl
              - libyaml-shell-perl
              - libyaml-tiny-perl
              - php-yaml
              - libcyaml-dev
              - libcyaml1
              - libfyaml-dev
              - libfyaml-utils
              - libfyaml0
              - liblz4-1
              - liblz4-dev
              - liblz4-tool
              - lz4
              - lz4json
              - freeipmi
              - freeipmi-common
              - freeipmi-bmc-watchdog
              - freeipmi-ipmidetect
              - freeipmi-tools
              - libfreeipmi-dev
              - libipmiconsole-dev
              - libipmiconsole2
              - numactl
              - libnuma-dev
              - libnuma1
              - numatop
              - libipmimonitoring-dev
              - libipmimonitoring6
              - liblua5.4-0
              - liblua5.4-dev
              - lua-argparse
              - lua-bit32
              - lua-bit32-dev
              - lua-bitop
              - lua-bitop-dev
              - lua-cjson
              - lua-cjson-dev
              - lua-json
              - lua-curl
              - lua-curl-dev
              - lua-curses
              - lua-curses-dev
              - lua-event
              - lua-event-dev
              - lua-expat
              - lua-expat-dev
              - lua-filesystem
              - lua-filesystem-dev
              - lua-http
              - lua-inifile
              - lua-rrd
              - lua-rrd-dev
              - lua-readline
              - lua-readline-dev
              - lua-sec
              - lua-sec-dev
              - lua-xmlrpc
              - lua-yaml
              - lua-yaml-dev
              - lua-zip
              - lua-zip-dev
              - lua-zlib
              - lua-zlib-dev
            state: present
            update_cache: true 
        - name: extract slurm archive
          ansible.builtin.unarchive:
            dest: /home/lory/building/
            remote_src: true
            src: /home/lory/archive/slurm-24.11.6.tar.bz2
            creates: /home/lory/building/slurm-24.11.6/configure
        - name: building modules
          ansible.builtin.shell:
            cmd: |-
              set -eo pipefail
              source /etc/bash.bashrc
              source /etc/profile.d/modules.sh
              module load cuda-12.9.1 gcc-13.4.0 ucx-1.18.1 pmix-5.0.8 ucx-1.18.1
              ./configure --prefix=/home/lory/sw_install/gcc-13.4.0/slurm-24.11.6 --enable-shared=yes --enable-static=yes --enable-dependency-tracking --enable-load-env-no-login --with-mysql_config --with-json --with-jwt --with-http-parser --with-yaml --with-hdf5 --with-lz4 --with-freeipmi --with-rdkafka --with-munge --with-libcurl --with-lua --with-bpf --without-s2n --enable-cgroupv2 --enable-pam --enable-pkgconfig --with-pkgconfigdir --enable-salloc-kill-cmd --disable-selinux --enable-sview --enable-optimizations --enable-x11 --with-nvml=/home/lory/sw_install/nvidia/cuda-12.9.1 --with-hwloc=/home/lory/sw_install/gcc-13.4.0/hwloc-2.12.1 --with-pmix=/home/lory/sw_install/gcc-13.4.0/pmix-5.0.8 --with-ucx=/home/lory/sw_install/gcc-13.4.0/ucx-1.18.1
              make -j 6
              make install
            chdir: /home/lory/building/slurm-24.11.6
            creates: /home/lory/sw_install/gcc-13.4.0/slurm-24.11.6/lib/libslurm.la
            executable: /bin/bash
        - name: Remove building file
          ansible.builtin.file:
            path: /home/lory/building/slurm-24.11.6
            state: absent
    - name: Copy slurm modules to ansible
      ansible.builtin.copy:
        src: slurm-24.11.6
        dest: /home/lory/modulefiles/libs/
